"""Prebuilt Instagram post bank for gym content targets."""

TARGET_CONTENT = {
    "weightloss": [
        {"caption": "Day 1: Start your fat-loss journey with a 30-minute full-body circuit. Small steps create big results.", "image_idea": "Trainer guiding beginners through circuit stations.", "hashtags": "#WeightLoss #HyderabadFitness #FatLossJourney #GymMotivation #FitTelangana"},
        {"caption": "Day 2: Focus on hydration and steps today. Aim 8,000+ steps and keep your energy high.", "image_idea": "Member walking on treadmill with water bottle.", "hashtags": "#WeightLossTips #HealthyHabits #GymLife #Hydration #FitnessGoals"},
        {"caption": "Day 3: Strength training boosts metabolism. Add compound lifts to your routine.", "image_idea": "Barbell squat setup with coach support.", "hashtags": "#MetabolismBoost #StrengthForFatLoss #HyderabadGym #WorkoutSmart #GymResults"},
        {"caption": "Day 4: Meal prep wins fat loss. Plan protein-rich meals before your busy week.", "image_idea": "Meal prep containers with grilled protein and veggies.", "hashtags": "#FatLossNutrition #MealPrep #GymDiet #WeightLossIndia #FitnessLifestyle"},
        {"caption": "Day 5: Add 10 minutes of incline cardio after lifting for extra calorie burn.", "image_idea": "Incline treadmill session after strength workout.", "hashtags": "#CardioTips #CalorieBurn #WeightLossPlan #TrainInHyderabad #FitnessDiscipline"},
        {"caption": "Day 6: Sleep is your secret weapon. Recovery helps your body burn fat efficiently.", "image_idea": "Recovery-themed gym corner with stretching and calm lights.", "hashtags": "#RecoveryMatters #SleepForResults #FatLossSupport #GymCoach #HealthyRoutine"},
        {"caption": "Day 7: Weekend challenge: no sugary drinks. Choose water, lemon water, or black coffee.", "image_idea": "Healthy drink choices display at gym cafe area.", "hashtags": "#WeekendChallenge #NoSugar #WeightLossMindset #FitnessHabits #GymCommunity"},
        {"caption": "Day 8: Core day! Strong core improves form and keeps training safe.", "image_idea": "Members doing planks and controlled core exercises.", "hashtags": "#CoreWorkout #FatLossTraining #GymSafety #HyderabadFitFam #PostureMatters"},
        {"caption": "Day 9: Progress check: inches lost, energy gained, confidence rising.", "image_idea": "Coach noting body measurements and smiling member.", "hashtags": "#ProgressCheck #WeightLossJourney #GymTransformation #StayConsistent #FitnessProgress"},
        {"caption": "Day 10: Celebrate discipline over perfection. You showed up, and that is success.", "image_idea": "Group photo after session with milestone board.", "hashtags": "#ConsistencyWins #WeightLossSuccess #GymMotivationDaily #FitHyderabad #StrongerEveryday"},
    ],
    "fitness": [
        {"caption": "Day 1: Build your fitness base with balanced strength + cardio training.", "image_idea": "Split screen of weights and treadmill.", "hashtags": "#FitnessTraining #GymInHyderabad #HealthyLifestyle #FitTelangana #WorkoutPlan"},
        {"caption": "Day 2: Train mobility today to move better and reduce injury risk.", "image_idea": "Dynamic mobility drills with coach demonstration.", "hashtags": "#MobilityWork #TrainBetter #GymWellness #FitnessIndia #MovementMatters"},
        {"caption": "Day 3: Full-body functional workout for real-life strength and stamina.", "image_idea": "Battle ropes and kettlebell functional zone.", "hashtags": "#FunctionalFitness #StrengthAndStamina #HyderabadGyms #FitLife #GymTraining"},
        {"caption": "Day 4: Consistency > intensity. Show up and complete your session.", "image_idea": "Check-in desk with attendance streak display.", "hashtags": "#Consistency #FitnessRoutine #GymDiscipline #DailyWorkout #FitnessMindset"},
        {"caption": "Day 5: Add short HIIT intervals to improve endurance and performance.", "image_idea": "Sprint interval timer on gym screen.", "hashtags": "#HIITWorkout #EnduranceTraining #CardioFitness #TrainHard #GymEnergy"},
        {"caption": "Day 6: Weekend recovery walk + stretching = better Monday workout.", "image_idea": "Members stretching in cool-down zone.", "hashtags": "#RecoveryDay #ActiveLifestyle #Stretching #FitnessRecovery #HealthyBody"},
        {"caption": "Day 7: Improve your pushups and planks today for upper-body control.", "image_idea": "Trainer correcting pushup form.", "hashtags": "#BodyweightTraining #CoreStrength #FitnessForm #HyderabadFit #GymTips"},
        {"caption": "Day 8: Fuel your training with protein, fiber, and hydration.", "image_idea": "Nutrition counter with healthy meal examples.", "hashtags": "#FitnessNutrition #TrainAndFuel #HealthyEating #GymDiet #PerformanceFood"},
        {"caption": "Day 9: Track your reps and sets to measure real progress.", "image_idea": "Workout journal and dumbbell rack.", "hashtags": "#TrackProgress #FitnessGoals #WorkoutJournal #GymResults #StayFocused"},
        {"caption": "Day 10: Fitness is a lifestyle. Keep the momentum and level up.", "image_idea": "Confident member finishing session with fist pump.", "hashtags": "#FitnessLifestyle #Momentum #GymMotivation #FitCommunity #TrainSmart"},
    ],
    "weightgain": [
        {"caption": "Day 1: Begin your healthy weight-gain phase with a structured strength plan.", "image_idea": "Coach setting progressive overload plan board.", "hashtags": "#WeightGain #MuscleBuilding #HyderabadGym #StrengthPlan #FitnessJourney"},
        {"caption": "Day 2: Increase calories smartly with quality carbs and lean protein.", "image_idea": "Meal with rice, paneer/chicken, and vegetables.", "hashtags": "#WeightGainDiet #CalorieSurplus #GymNutrition #BuildMass #HealthyEating"},
        {"caption": "Day 3: Train heavy basics: squat, bench, deadlift progression.", "image_idea": "Barbell training in strength zone.", "hashtags": "#StrengthTraining #MassGain #HyderabadFitness #CompoundLifts #GymProgress"},
        {"caption": "Day 4: Add a protein-rich post-workout meal within 60 minutes.", "image_idea": "Post-workout shake and whole-food plate.", "hashtags": "#PostWorkout #ProteinPower #WeightGainTips #RecoveryFuel #GymLifestyle"},
        {"caption": "Day 5: Focus on sleep and recovery to maximize muscle growth.", "image_idea": "Recovery message board with sleep target.", "hashtags": "#MuscleRecovery #SleepForGains #GymScience #WeightGainJourney #TrainRecoverGrow"},
        {"caption": "Day 6: Add one extra snack today: nuts, fruit, yogurt, and protein.", "image_idea": "Healthy snack tray for bulking.", "hashtags": "#HealthyBulking #CalorieDense #NutritionTips #GymIndia #MassBuilding"},
        {"caption": "Day 7: Form first, then load. Proper technique grows better muscle.", "image_idea": "Trainer assisting with barbell row form.", "hashtags": "#LiftWithForm #BuildMuscle #GymCoaching #StrengthGoals #TrainSafe"},
        {"caption": "Day 8: Track bodyweight weekly, not daily, for smarter progress.", "image_idea": "Progress chart with weekly check-ins.", "hashtags": "#TrackYourGains #WeightGainPlan #FitnessTracking #GymResults #BulkSeason"},
        {"caption": "Day 9: Push intensity with one extra set on major lifts.", "image_idea": "Member finishing final heavy set.", "hashtags": "#ProgressiveOverload #MuscleGrowth #StrengthSession #HyderabadGyms #FitnessDiscipline"},
        {"caption": "Day 10: Celebrate strength wins: better reps, better confidence.", "image_idea": "PR board update with smiling member.", "hashtags": "#StrengthWins #WeightGainSuccess #GymMotivation #MassGainJourney #StayConsistent"},
    ],
    "strength": [
        {"caption": "Day 1: Strength block starts now. Focus on squat depth and control.", "image_idea": "Coach cueing squat form from side angle.", "hashtags": "#StrengthTraining #SquatDay #HyderabadGym #PowerBuilding #TrainHard"},
        {"caption": "Day 2: Bench press technique day: stable setup and strong drive.", "image_idea": "Bench press setup with spotter support.", "hashtags": "#BenchPress #StrengthGoals #GymTechnique #FitTelangana #LiftHeavy"},
        {"caption": "Day 3: Deadlift fundamentals: bracing, hinge, and bar path.", "image_idea": "Deadlift coaching with bar path markers.", "hashtags": "#DeadliftDay #StrengthCoach #GymProgress #PowerTraining #FormMatters"},
        {"caption": "Day 4: Accessory work builds long-term strength resilience.", "image_idea": "Romanian deadlift and rowing accessory circuit.", "hashtags": "#AccessoryWork #InjuryPrevention #StrengthProgram #GymIndia #BuildStrong"},
        {"caption": "Day 5: Track bar speed and quality, not just load.", "image_idea": "Athlete performing controlled explosive reps.", "hashtags": "#StrengthMetrics #PowerOutput #SmartTraining #HyderabadFitFam #GymScience"},
        {"caption": "Day 6: Deload smartly when needed to avoid plateaus.", "image_idea": "Light training session with mobility drills.", "hashtags": "#DeloadWeek #TrainSmart #StrengthJourney #GymRecovery #LongTermGains"},
        {"caption": "Day 7: Grip and core carry your heavy lifts. Train both.", "image_idea": "Farmer carry and plank superset station.", "hashtags": "#GripStrength #CorePower #HeavyLifting #FitnessPerformance #GymTips"},
        {"caption": "Day 8: Add pauses to improve control in big movements.", "image_idea": "Paused squat and paused bench clips.", "hashtags": "#PausedReps #StrengthControl #TechniqueFirst #HyderabadStrength #GymTraining"},
        {"caption": "Day 9: Push your top set, then back-off sets for volume.", "image_idea": "Barbell plates increasing across sets.", "hashtags": "#TopSet #BackOffSets #StrengthCycle #PowerGym #ProgressiveTraining"},
        {"caption": "Day 10: End the cycle proud. New numbers, stronger mindset.", "image_idea": "Athlete celebrating new PR with coach.", "hashtags": "#PersonalRecord #StrengthSuccess #GymMotivation #LiftWithPurpose #StrongerToday"},
    ],
    "muscle_building": [
        {"caption": "Day 1: Hypertrophy phase begins. Target controlled reps and full range.", "image_idea": "Dumbbell press with tempo guidance.", "hashtags": "#MuscleBuilding #Hypertrophy #GymInHyderabad #TrainForSize #FitnessResults"},
        {"caption": "Day 2: Prioritize protein at every meal for muscle repair.", "image_idea": "High-protein meal spread near gym cafe.", "hashtags": "#ProteinIntake #MuscleGrowth #GymNutrition #BuildLeanMass #FitnessIndia"},
        {"caption": "Day 3: Chest and back superset day for volume and pump.", "image_idea": "Lat pulldown + incline press sequence.", "hashtags": "#PushPull #MusclePump #GymVolume #HyderabadFit #TrainHarder"},
        {"caption": "Day 4: Tempo training improves muscle tension and control.", "image_idea": "Slow eccentric bicep curl demonstration.", "hashtags": "#TimeUnderTension #HypertrophyTraining #MuscleFocus #GymTechnique #GrowthMindset"},
        {"caption": "Day 5: Add one set per muscle group this week for progression.", "image_idea": "Workout tracker with volume increase notes.", "hashtags": "#TrainingVolume #ProgressiveOverload #MuscleGain #GymGoals #StrengthAndSize"},
        {"caption": "Day 6: Recovery nutrition supports growth - do not skip meals.", "image_idea": "Post-workout meal prep and shake station.", "hashtags": "#RecoveryNutrition #MuscleRecovery #GymDietPlan #FitnessLifestyle #BulkSmart"},
        {"caption": "Day 7: Leg day builds your base. Train with intent.", "image_idea": "Leg press and lunges with trainer cues.", "hashtags": "#LegDay #BuildYourBase #MuscleBuildingIndia #GymWork #NoSkippedLegDay"},
        {"caption": "Day 8: Improve mind-muscle connection for better activation.", "image_idea": "Cable fly and focused contraction close-up.", "hashtags": "#MindMuscleConnection #HypertrophyTips #GymCoaching #TrainFocused #MuscleActivation"},
        {"caption": "Day 9: Keep rest periods disciplined for optimal hypertrophy.", "image_idea": "Timer app between machine sets.", "hashtags": "#RestIntervals #MuscleGrowthPlan #GymDiscipline #WorkoutStructure #FitTelangana"},
        {"caption": "Day 10: Document your progress photos and strength markers.", "image_idea": "Member checking progress wall chart.", "hashtags": "#ProgressPhotos #MuscleBuildingJourney #FitnessTracking #GymSuccess #StayConsistent"},
    ],
    "fat_loss": [
        {"caption": "Day 1: Start with a calorie-aware routine and daily movement target.", "image_idea": "Coach discussing fat-loss roadmap with member.", "hashtags": "#FatLoss #FitnessHyderabad #HealthyTransformation #GymRoutine #StartToday"},
        {"caption": "Day 2: Prioritize high-protein meals to stay full and preserve muscle.", "image_idea": "Balanced fat-loss meal prep layout.", "hashtags": "#FatLossNutrition #HighProtein #GymDiet #BodyRecomp #HealthyEating"},
        {"caption": "Day 3: Interval training day for efficient calorie burn.", "image_idea": "Rower or bike interval sprint timer.", "hashtags": "#IntervalTraining #CalorieDeficit #GymCardio #FitIndia #WorkoutEnergy"},
        {"caption": "Day 4: Lift weights to support fat loss and body shape.", "image_idea": "Dumbbell strength set with form coaching.", "hashtags": "#LiftForFatLoss #StrengthAndLean #GymTips #HyderabadFitFam #TransformationPlan"},
        {"caption": "Day 5: Avoid liquid calories and choose whole foods.", "image_idea": "Sugar drinks crossed out beside water bottle.", "hashtags": "#FatLossHabits #WholeFoods #NutritionCoaching #GymSuccess #StayLean"},
        {"caption": "Day 6: Weekend activity challenge: 10k steps and light mobility.", "image_idea": "Step tracker screenshot and stretching mat.", "hashtags": "#StepChallenge #ActiveWeekend #FatLossJourney #HealthyLifestyle #MoveMore"},
        {"caption": "Day 7: Check non-scale wins: energy, sleep, and confidence.", "image_idea": "Member testimonial card at gym wall.", "hashtags": "#NonScaleVictory #FitnessMindset #FatLossProgress #GymCommunity #Consistency"},
        {"caption": "Day 8: Plan meals before social events to stay on track.", "image_idea": "Meal planning notebook with grocery list.", "hashtags": "#PlanToSucceed #FatLossCoach #SmartNutrition #GymLifestyle #FitnessDiscipline"},
        {"caption": "Day 9: Keep workouts simple: push, pull, squat, hinge.", "image_idea": "Whiteboard showing basic movement pattern split.", "hashtags": "#TrainingBasics #FatLossWorkout #GymProgram #TrainSmart #ResultsDriven"},
        {"caption": "Day 10: You do not need perfection, only consistency.", "image_idea": "Motivation wall quote with gym members training.", "hashtags": "#ConsistencyOverPerfection #FatLossMotivation #HyderabadGyms #StayCommitted #HealthyProgress"},
    ],
    "cardio_endurance": [
        {"caption": "Day 1: Cardio base day - moderate pace for 25-30 minutes.", "image_idea": "Treadmill zone with heart-rate monitor display.", "hashtags": "#CardioEndurance #StaminaBuilding #HyderabadFitness #RunStronger #GymCardio"},
        {"caption": "Day 2: Add interval bursts to build speed and conditioning.", "image_idea": "Sprint intervals on assault bike.", "hashtags": "#IntervalCardio #Conditioning #EnduranceTraining #GymPerformance #FitTelangana"},
        {"caption": "Day 3: Cross-train using rower and cycle to reduce monotony.", "image_idea": "Member switching between rower and spin bike.", "hashtags": "#CrossTraining #CardioVariety #StaminaGoals #GymRoutine #TrainSmart"},
        {"caption": "Day 4: Breathing rhythm improves endurance. Focus on control.", "image_idea": "Coach guiding breathing drills post-cardio.", "hashtags": "#BreathingTechnique #EnduranceTips #CardioCoach #FitnessProgress #WorkoutScience"},
        {"caption": "Day 5: Tempo cardio day to improve sustained effort.", "image_idea": "Member running at steady challenging pace.", "hashtags": "#TempoRun #CardioFitness #StaminaWork #GymInHyderabad #PerformanceTraining"},
        {"caption": "Day 6: Recovery cardio: easy pace + mobility flow.", "image_idea": "Low-intensity incline walk and stretching.", "hashtags": "#ActiveRecovery #EndurancePlan #CardioBalance #GymRecovery #HealthyTraining"},
        {"caption": "Day 7: Improve leg endurance with sled pushes and lunges.", "image_idea": "Sled push lane and weighted walking lunges.", "hashtags": "#LegEndurance #ConditioningWorkout #FunctionalCardio #GymChallenge #TrainHard"},
        {"caption": "Day 8: Track heart-rate zones for smarter cardio sessions.", "image_idea": "Heart-rate chart on smartwatch app.", "hashtags": "#HeartRateTraining #CardioZones #FitnessData #EnduranceJourney #GymResults"},
        {"caption": "Day 9: Long-duration cardio builds mental resilience too.", "image_idea": "Member finishing a long steady cardio block.", "hashtags": "#MentalStrength #LongCardio #StaminaMindset #FitnessGoals #NeverQuit"},
        {"caption": "Day 10: Endurance improves one session at a time. Keep going.", "image_idea": "Before-after endurance challenge scoreboard.", "hashtags": "#CardioProgress #EnduranceSuccess #GymMotivation #FitHyderabad #StrongerEveryDay"},
    ],
    "womens_fitness": [
        {"caption": "Day 1: Strong is beautiful. Start with confidence and purpose.", "image_idea": "Women-led strength class in progress.", "hashtags": "#WomensFitness #StrongWomen #HyderabadGym #FitnessCommunity #TrainConfident"},
        {"caption": "Day 2: Lower-body strength day for power and stability.", "image_idea": "Squats and glute bridge setup with coach.", "hashtags": "#LowerBodyWorkout #WomenWhoLift #GymInTelangana #StrengthGoals #FitLifestyle"},
        {"caption": "Day 3: Core and posture session to move better every day.", "image_idea": "Pilates-inspired core drills in studio corner.", "hashtags": "#CoreStrength #PostureTraining #WomensHealth #GymRoutine #MoveBetter"},
        {"caption": "Day 4: Nutrition check-in: balance protein, fiber, and hydration.", "image_idea": "Healthy meal consult with female trainer.", "hashtags": "#WomensNutrition #HealthyHabits #GymSupport #FitnessCoach #BodyPositive"},
        {"caption": "Day 5: Cardio + strength combo for fat loss and energy.", "image_idea": "Circuit class with step-ups and dumbbells.", "hashtags": "#WomensWorkout #CardioStrength #HyderabadFitWomen #FitnessEnergy #GymLife"},
        {"caption": "Day 6: Recovery day with stretching and mindful breathing.", "image_idea": "Group stretch flow session.", "hashtags": "#RecoveryDay #WellnessRoutine #WomensWellness #GymRecovery #SelfCare"},
        {"caption": "Day 7: Build upper-body confidence with push and pull training.", "image_idea": "Lat pulldown and dumbbell press station.", "hashtags": "#UpperBodyStrength #WomenInFitness #StrongAndHealthy #GymMotivation #TrainSmart"},
        {"caption": "Day 8: Focus on progressive overload safely and consistently.", "image_idea": "Member increasing dumbbell weight with trainer.", "hashtags": "#ProgressiveOverload #StrengthProgress #WomensGym #FitnessResults #ConsistencyWins"},
        {"caption": "Day 9: Celebrate every milestone, no matter how small.", "image_idea": "Milestone board with women member achievements.", "hashtags": "#FitnessMilestones #WomensCommunity #GymWins #BodyConfidence #KeepGoing"},
        {"caption": "Day 10: You are stronger than you think. Keep showing up.", "image_idea": "Motivational group photo after session.", "hashtags": "#WomensFitnessJourney #StrongMindStrongBody #HyderabadWomen #GymInspiration #FitnessForever"},
    ],
    "senior_fitness": [
        {"caption": "Day 1: Healthy aging starts with gentle movement and consistency.", "image_idea": "Senior-friendly guided exercise class.", "hashtags": "#SeniorFitness #HealthyAging #HyderabadHealth #ActiveLifestyle #MoveDaily"},
        {"caption": "Day 2: Mobility and balance work reduces fall risk.", "image_idea": "Balance drill with support bars and trainer.", "hashtags": "#BalanceTraining #MobilityForSeniors #FitnessSafety #GymCare #Wellness"},
        {"caption": "Day 3: Light strength training supports bone and joint health.", "image_idea": "Resistance band and light dumbbell exercises.", "hashtags": "#StrengthForSeniors #BoneHealth #ActiveAging #GymSupport #HealthyBody"},
        {"caption": "Day 4: Walking-based cardio boosts heart health.", "image_idea": "Group treadmill walk at comfortable pace.", "hashtags": "#HeartHealth #SeniorCardio #FitnessForLife #HyderabadGym #StayActive"},
        {"caption": "Day 5: Breathing and flexibility improve daily comfort.", "image_idea": "Seated stretch and breathing practice.", "hashtags": "#Flexibility #BreathingExercises #SeniorWellness #GymRoutine #FeelBetter"},
        {"caption": "Day 6: Stay hydrated and eat nutrient-dense meals.", "image_idea": "Hydration station and diet consultation visual.", "hashtags": "#SeniorNutrition #HydrationTips #HealthyHabits #WellnessJourney #GymGuidance"},
        {"caption": "Day 7: Functional movements help everyday independence.", "image_idea": "Sit-to-stand and step-up functional drills.", "hashtags": "#FunctionalFitness #IndependentLiving #SeniorStrength #GymTraining #ActiveSenior"},
        {"caption": "Day 8: Social fitness classes improve mood and motivation.", "image_idea": "Smiling senior group class interaction.", "hashtags": "#CommunityFitness #SeniorCommunity #StayMotivated #HealthyMind #GymFamily"},
        {"caption": "Day 9: Track progress in stamina and balance each week.", "image_idea": "Trainer reviewing simple progress chart.", "hashtags": "#ProgressTracking #SeniorHealth #FitnessProgress #Consistency #WellAging"},
        {"caption": "Day 10: Every session is an investment in long-term health.", "image_idea": "Celebration photo with senior members and coaches.", "hashtags": "#HealthyAgingJourney #SeniorFitnessSuccess #GymMotivation #TelanganaHealth #KeepMoving"},
    ],
    "athletic_performance": [
        {"caption": "Day 1: Build your base with mobility, power, and movement prep.", "image_idea": "Athlete doing dynamic warm-up and jumps.", "hashtags": "#AthleticPerformance #SportsFitness #HyderabadAthletes #TrainLikeAnAthlete #Power"},
        {"caption": "Day 2: Speed day - short sprints with full recovery.", "image_idea": "Sprint lane timing session.", "hashtags": "#SpeedTraining #AthleteDevelopment #ExplosivePower #GymPerformance #TrainFast"},
        {"caption": "Day 3: Strength day supports force production and resilience.", "image_idea": "Trap-bar deadlift with coach.", "hashtags": "#AthleteStrength #ForceProduction #SportsTraining #HyderabadGym #PerformanceGoals"},
        {"caption": "Day 4: Agility and reaction drills improve game performance.", "image_idea": "Cone drills and reaction lights setup.", "hashtags": "#AgilityTraining #ReactionSpeed #SportsConditioning #AthleticGym #GameReady"},
        {"caption": "Day 5: Core rotation and anti-rotation work for stability.", "image_idea": "Cable core rotation sequence.", "hashtags": "#CorePerformance #AthleteCore #InjuryPrevention #StrengthAndSpeed #FitnessCoaching"},
        {"caption": "Day 6: Recovery protocol: mobility, soft tissue, hydration.", "image_idea": "Foam rolling and stretch station.", "hashtags": "#AthleteRecovery #SportsWellness #TrainRecoverPerform #GymScience #PerformanceCare"},
        {"caption": "Day 7: Plyometric day for explosiveness and coordination.", "image_idea": "Box jumps and lateral bounds drills.", "hashtags": "#Plyometrics #ExplosiveTraining #AthleticPower #GymAthlete #PerformanceTraining"},
        {"caption": "Day 8: Conditioning intervals to sustain high match intensity.", "image_idea": "Athlete interval run with timer and heart-rate check.", "hashtags": "#SportsConditioning #EnduranceForAthletes #GameFitness #TrainHard #FitTelangana"},
        {"caption": "Day 9: Technique + strength combination builds complete athletes.", "image_idea": "Coach-led mixed session with skill and lift blocks.", "hashtags": "#CompleteAthlete #SkillAndStrength #SportsGym #AthleticProgress #CoachDriven"},
        {"caption": "Day 10: Peak week mindset: discipline, focus, execution.", "image_idea": "Athlete focus portrait before training set.", "hashtags": "#PeakPerformance #AthleteMindset #SportsSuccess #HyderabadSports #RiseAndPerform"},
    ],
}
